<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Poison Menu</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    
    <TargetFramework>netstandard2.1</TargetFramework>
	  <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>

    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>

    <Configurations>Debug;Release;Legal;Legal Debug;Legal Debug</Configurations>
  </PropertyGroup>

  <PropertyGroup>
    <ManagedGameRefs Condition="Exists('$(GameAssemblyPath)\Assembly-CSharp.dll')">$(GameAssemblyPath)</ManagedGameRefs>
    <ManagedGameRefs Condition="!Exists('$(GameAssemblyPath)\Assembly-CSharp.dll')">$(ProjectDir)References\Managed</ManagedGameRefs>
    <CoreGameRefs Condition="Exists('$(BepInExAssemblyPath)\BepInEx.dll')">$(BepInExAssemblyPath)</CoreGameRefs>
    <CoreGameRefs Condition="!Exists('$(BepInExAssemblyPath)\BepInEx.dll')">$(ProjectDir)References\core</CoreGameRefs>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Legal'">
    <AssemblyName>Poison Menu Legal</AssemblyName>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Legal Debug'">
    <AssemblyName>Poison Menu Legal Debug</AssemblyName>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'LEGAL_DEBUG'">
    <AssemblyName>Poison Menu Legal Debug</AssemblyName>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'DEBUG' Or '$(Configuration)' == 'Debug'">
    <AssemblyName>Poison Menu Debug</AssemblyName>
  </PropertyGroup>
  
  <PropertyGroup> 
    <StartAction>Program</StartAction>
    <StartProgram>C:\Windows\explorer.exe</StartProgram>
    <StartArguments>steam://run/1533390</StartArguments>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="LICENSE" />
    <None Remove="Resources\Client\*" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="LICENSE" />
    <EmbeddedResource Include="Resources\Client\*" />
  </ItemGroup>

  <!-- AssemblyPublicizer usage inspired from GorillaShirts -->
  <ItemGroup>
	  <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.3">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	</ItemGroup>
  
  <PropertyGroup>
    <PublicizerClearCacheOnClean>true</PublicizerClearCacheOnClean>
  </PropertyGroup>
	
  <ItemGroup>
    <Reference Include="Assembly-CSharp" Publicize="true">
      <HintPath>$(ManagedGameRefs)\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(CoreGameRefs)\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="AA.Mothership" Publicize="true">
      <HintPath>$(ManagedGameRefs)\AA.Mothership.dll</HintPath>
    </Reference>
    <Reference Include="ALINE">
      <HintPath>$(ManagedGameRefs)\ALINE.dll</HintPath>
    </Reference>
    <Reference Include="andywiecko.BurstTriangulator">
      <HintPath>$(ManagedGameRefs)\andywiecko.BurstTriangulator.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>$(ManagedGameRefs)\Assembly-CSharp-firstpass.dll</HintPath>
    </Reference>
    <Reference Include="AssistantCoreSDKRuntime">
      <HintPath>$(ManagedGameRefs)\AssistantCoreSDKRuntime.dll</HintPath>
    </Reference>
    <Reference Include="AstarPathfindingProject">
      <HintPath>$(ManagedGameRefs)\AstarPathfindingProject.dll</HintPath>
    </Reference>
    <Reference Include="Autodesk.Fbx">
      <HintPath>$(ManagedGameRefs)\Autodesk.Fbx.dll</HintPath>
    </Reference>
    <Reference Include="Backtrace.Unity">
      <HintPath>$(ManagedGameRefs)\Backtrace.Unity.dll</HintPath>
    </Reference>
    <Reference Include="BakeryRuntimeAssembly">
      <HintPath>$(ManagedGameRefs)\BakeryRuntimeAssembly.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>$(CoreGameRefs)\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Harmony">
      <HintPath>$(CoreGameRefs)\BepInEx.Harmony.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Preloader">
      <HintPath>$(CoreGameRefs)\BepInEx.Preloader.dll</HintPath>
    </Reference>
    <Reference Include="Modio">
      <HintPath>$(ManagedGameRefs)\Modio.dll</HintPath>
    </Reference>
    <Reference Include="Modio.Unity">
      <HintPath>$(ManagedGameRefs)\Modio.Unity.dll</HintPath>
    </Reference>
    <Reference Include="Modio.Unity.Examples">
      <HintPath>$(ManagedGameRefs)\Modio.Unity.Examples.dll</HintPath>
    </Reference>
    <Reference Include="Modio.Unity.UI">
      <HintPath>$(ManagedGameRefs)\Modio.Unity.UI.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Cinemachine">
      <HintPath>$(ManagedGameRefs)\Unity.Cinemachine.dll</HintPath>
    </Reference>
    <Reference Include="Fusion.Common">
      <HintPath>$(ManagedGameRefs)\Fusion.Common.dll</HintPath>
    </Reference>
    <Reference Include="Fusion.Log">
      <HintPath>$(ManagedGameRefs)\Fusion.Log.dll</HintPath>
    </Reference>
    <Reference Include="Fusion.Realtime">
      <HintPath>$(ManagedGameRefs)\Fusion.Realtime.dll</HintPath>
    </Reference>
    <Reference Include="Fusion.Runtime">
      <HintPath>$(ManagedGameRefs)\Fusion.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Fusion.Sockets">
      <HintPath>$(ManagedGameRefs)\Fusion.Sockets.dll</HintPath>
    </Reference>
    <Reference Include="Fusion.Unity">
      <HintPath>$(ManagedGameRefs)\Fusion.Unity.dll</HintPath>
    </Reference>
    <Reference Include="geometry3Sharp">
      <HintPath>$(ManagedGameRefs)\geometry3Sharp.dll</HintPath>
    </Reference>
    <Reference Include="GT_CustomMapSupportRuntime">
      <HintPath>$(ManagedGameRefs)\GT_CustomMapSupportRuntime.dll</HintPath>
    </Reference>
    <Reference Include="HarmonyXInterop">
      <HintPath>$(CoreGameRefs)\HarmonyXInterop.dll</HintPath>
    </Reference>
    <Reference Include="KID">
      <HintPath>$(ManagedGameRefs)\KID.dll</HintPath>
    </Reference>
    <Reference Include="LIV.LCK" Publicize="true">
      <HintPath>$(ManagedGameRefs)\LIV.LCK.dll</HintPath>
    </Reference>
    <Reference Include="LIV.LCK_GorillaTag">
      <HintPath>$(ManagedGameRefs)\LIV.LCK_GorillaTag.dll</HintPath>
    </Reference>
    <Reference Include="LIV.NativeAudioBridge">
      <HintPath>$(ManagedGameRefs)\LIV.NativeAudioBridge.dll</HintPath>
    </Reference>
	<Reference Include="MelonLoader">
      <HintPath>$(ProjectDir)References\core\MelonLoader.dll</HintPath>
    </Reference>
    <Reference Include="MeshBakerCore">
      <HintPath>$(ManagedGameRefs)\MeshBakerCore.dll</HintPath>
    </Reference>
    <Reference Include="Meta.WitAi">
      <HintPath>$(ManagedGameRefs)\Meta.WitAi.dll</HintPath>
    </Reference>
    <Reference Include="Meta.WitAi.Lib">
      <HintPath>$(ManagedGameRefs)\Meta.WitAi.Lib.dll</HintPath>
    </Reference>
    <Reference Include="Meta.WitAi.TTS">
      <HintPath>$(ManagedGameRefs)\Meta.WitAi.TTS.dll</HintPath>
    </Reference>
    <Reference Include="Meta.XR.BuildingBlocks">
      <HintPath>$(ManagedGameRefs)\Meta.XR.BuildingBlocks.dll</HintPath>
    </Reference>
    <Reference Include="Mono.Cecil">
      <HintPath>$(CoreGameRefs)\Mono.Cecil.dll</HintPath>
    </Reference>
    <Reference Include="Mono.Cecil.Mdb">
      <HintPath>$(CoreGameRefs)\Mono.Cecil.Mdb.dll</HintPath>
    </Reference>
    <Reference Include="Mono.Cecil.Pdb">
      <HintPath>$(CoreGameRefs)\Mono.Cecil.Pdb.dll</HintPath>
    </Reference>
    <Reference Include="Mono.Cecil.Rocks">
      <HintPath>$(CoreGameRefs)\Mono.Cecil.Rocks.dll</HintPath>
    </Reference>
    <Reference Include="Mono.Security">
      <HintPath>$(ManagedGameRefs)\Mono.Security.dll</HintPath>
    </Reference>
    <Reference Include="MonoMod.RuntimeDetour">
      <HintPath>$(CoreGameRefs)\MonoMod.RuntimeDetour.dll</HintPath>
    </Reference>
    <Reference Include="MonoMod.Utils">
      <HintPath>$(CoreGameRefs)\MonoMod.Utils.dll</HintPath>
    </Reference>
    <Reference Include="NanoSockets">
      <HintPath>$(ManagedGameRefs)\NanoSockets.dll</HintPath>
    </Reference>
    <Reference Include="NavMeshComponents">
      <HintPath>$(ManagedGameRefs)\NavMeshComponents.dll</HintPath>
    </Reference>
    <Reference Include="Oculus.Interaction">
      <HintPath>$(ManagedGameRefs)\Oculus.Interaction.dll</HintPath>
    </Reference>
    <Reference Include="Oculus.Interaction.OVR">
      <HintPath>$(ManagedGameRefs)\Oculus.Interaction.OVR.dll</HintPath>
    </Reference>
    <Reference Include="Oculus.Interaction.OVR.Samples">
      <HintPath>$(ManagedGameRefs)\Oculus.Interaction.OVR.Samples.dll</HintPath>
    </Reference>
    <Reference Include="Oculus.Platform">
      <HintPath>$(ManagedGameRefs)\Oculus.Platform.dll</HintPath>
    </Reference>
    <Reference Include="Oculus.VR">
      <HintPath>$(ManagedGameRefs)\Oculus.VR.dll</HintPath>
    </Reference>
    <Reference Include="Pathfinding.ClipperLib">
      <HintPath>$(ManagedGameRefs)\Pathfinding.ClipperLib.dll</HintPath>
    </Reference>
    <Reference Include="Pathfinding.Ionic.Zip.Reduced">
      <HintPath>$(ManagedGameRefs)\Pathfinding.Ionic.Zip.Reduced.dll</HintPath>
    </Reference>
    <Reference Include="Pathfinding.Poly2Tri">
      <HintPath>$(ManagedGameRefs)\Pathfinding.Poly2Tri.dll</HintPath>
    </Reference>
    <Reference Include="Photon3Unity3D" Publicize="true">
      <HintPath>$(ManagedGameRefs)\Photon3Unity3D.dll</HintPath>
    </Reference>
    <Reference Include="PhotonRealtime" Publicize="true">
      <HintPath>$(ManagedGameRefs)\PhotonRealtime.dll</HintPath>
    </Reference>
    <Reference Include="PhotonUnityNetworking" Publicize="true">
      <HintPath>$(ManagedGameRefs)\PhotonUnityNetworking.dll</HintPath>
    </Reference>
    <Reference Include="PhotonUnityNetworking.Utilities">
      <HintPath>$(ManagedGameRefs)\PhotonUnityNetworking.Utilities.dll</HintPath>
    </Reference>
    <Reference Include="PhotonVoice" Publicize="true">
      <HintPath>$(ManagedGameRefs)\PhotonVoice.dll</HintPath>
    </Reference>
    <Reference Include="PhotonVoice.API" Publicize="true">
      <HintPath>$(ManagedGameRefs)\PhotonVoice.API.dll</HintPath>
    </Reference>
    <Reference Include="PhotonVoice.Fusion" Publicize="true">
      <HintPath>$(ManagedGameRefs)\PhotonVoice.Fusion.dll</HintPath>
    </Reference>
    <Reference Include="PhotonVoice.PUN" Publicize="true">
      <HintPath>$(ManagedGameRefs)\PhotonVoice.PUN.dll</HintPath>
    </Reference>
    <Reference Include="PlayFab" Publicize="true">
      <HintPath>$(ManagedGameRefs)\PlayFab.dll</HintPath>
    </Reference>
    <Reference Include="Sirenix.OdinInspector.Attributes">
      <HintPath>$(ManagedGameRefs)\Sirenix.OdinInspector.Attributes.dll</HintPath>
    </Reference>
    <Reference Include="Sirenix.OdinInspector.Modules.Unity.Addressables">
      <HintPath>$(ManagedGameRefs)\Sirenix.OdinInspector.Modules.Unity.Addressables.dll</HintPath>
    </Reference>
    <Reference Include="SteamVR">
      <HintPath>$(ManagedGameRefs)\SteamVR.dll</HintPath>
    </Reference>
    <Reference Include="SteamVR_Actions">
      <HintPath>$(ManagedGameRefs)\SteamVR_Actions.dll</HintPath>
    </Reference>
    <Reference Include="TechniePhysicsCreator">
      <HintPath>$(ManagedGameRefs)\TechniePhysicsCreator.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Addressables">
      <HintPath>$(ManagedGameRefs)\Unity.Addressables.dll</HintPath>
    </Reference>
    <Reference Include="Unity.AI.Navigation">
      <HintPath>$(ManagedGameRefs)\Unity.AI.Navigation.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Animation.Rigging">
      <HintPath>$(ManagedGameRefs)\Unity.Animation.Rigging.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Animation.Rigging.DocCodeExamples">
      <HintPath>$(ManagedGameRefs)\Unity.Animation.Rigging.DocCodeExamples.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Burst">
      <HintPath>$(ManagedGameRefs)\Unity.Burst.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Burst.Unsafe">
      <HintPath>$(ManagedGameRefs)\Unity.Burst.Unsafe.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Collections">
      <HintPath>$(ManagedGameRefs)\Unity.Collections.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Collections.LowLevel.ILSupport">
      <HintPath>$(ManagedGameRefs)\Unity.Collections.LowLevel.ILSupport.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Formats.Fbx.Runtime">
      <HintPath>$(ManagedGameRefs)\Unity.Formats.Fbx.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Unity.InputSystem">
      <HintPath>$(ManagedGameRefs)\Unity.InputSystem.dll</HintPath>
    </Reference>
    <Reference Include="Unity.InputSystem.ForUI">
      <HintPath>$(ManagedGameRefs)\Unity.InputSystem.ForUI.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Localization">
      <HintPath>$(ManagedGameRefs)\Unity.Localization.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Mathematics">
      <HintPath>$(ManagedGameRefs)\Unity.Mathematics.dll</HintPath>
    </Reference>
    <Reference Include="Unity.ProBuilder">
      <HintPath>$(ManagedGameRefs)\Unity.ProBuilder.dll</HintPath>
    </Reference>
    <Reference Include="Unity.ProBuilder.Csg">
      <HintPath>$(ManagedGameRefs)\Unity.ProBuilder.Csg.dll</HintPath>
    </Reference>
    <Reference Include="Unity.ProBuilder.KdTree">
      <HintPath>$(ManagedGameRefs)\Unity.ProBuilder.KdTree.dll</HintPath>
    </Reference>
    <Reference Include="Unity.ProBuilder.Poly2Tri">
      <HintPath>$(ManagedGameRefs)\Unity.ProBuilder.Poly2Tri.dll</HintPath>
    </Reference>
    <Reference Include="Unity.ProBuilder.Stl">
      <HintPath>$(ManagedGameRefs)\Unity.ProBuilder.Stl.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Profiling.Core">
      <HintPath>$(ManagedGameRefs)\Unity.Profiling.Core.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipeline.Universal.ShaderLibrary">
      <HintPath>$(ManagedGameRefs)\Unity.RenderPipeline.Universal.ShaderLibrary.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Core.Runtime">
      <HintPath>$(ManagedGameRefs)\Unity.RenderPipelines.Core.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Core.ShaderLibrary">
      <HintPath>$(ManagedGameRefs)\Unity.RenderPipelines.Core.ShaderLibrary.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.ShaderGraph.ShaderGraphLibrary">
      <HintPath>$(ManagedGameRefs)\Unity.RenderPipelines.ShaderGraph.ShaderGraphLibrary.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Universal.Runtime">
      <HintPath>$(ManagedGameRefs)\Unity.RenderPipelines.Universal.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Universal.Shaders">
      <HintPath>$(ManagedGameRefs)\Unity.RenderPipelines.Universal.Shaders.dll</HintPath>
    </Reference>
    <Reference Include="Unity.ResourceManager">
      <HintPath>$(ManagedGameRefs)\Unity.ResourceManager.dll</HintPath>
    </Reference>
    <Reference Include="Unity.ScriptableBuildPipeline">
      <HintPath>$(ManagedGameRefs)\Unity.ScriptableBuildPipeline.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Splines">
      <HintPath>$(ManagedGameRefs)\Unity.Splines.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(ManagedGameRefs)\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Timeline">
      <HintPath>$(ManagedGameRefs)\Unity.Timeline.dll</HintPath>
    </Reference>
    <Reference Include="Unity.XR.CoreUtils">
      <HintPath>$(ManagedGameRefs)\Unity.XR.CoreUtils.dll</HintPath>
    </Reference>
    <Reference Include="Unity.XR.Interaction.Toolkit">
      <HintPath>$(ManagedGameRefs)\Unity.XR.Interaction.Toolkit.dll</HintPath>
    </Reference>
    <Reference Include="Unity.XR.Management">
      <HintPath>$(ManagedGameRefs)\Unity.XR.Management.dll</HintPath>
    </Reference>
    <Reference Include="Unity.XR.OpenVR">
      <HintPath>$(ManagedGameRefs)\Unity.XR.OpenVR.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(ManagedGameRefs)\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AccessibilityModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.AccessibilityModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AIModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.AIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AndroidJNIModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.AndroidJNIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.AnimationModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ARModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.ARModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.AssetBundleModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.AudioModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ClothModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.ClothModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ClusterInputModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.ClusterInputModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ClusterRendererModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.ClusterRendererModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ContentLoadModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.ContentLoadModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CrashReportingModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.CrashReportingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.DirectorModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.DirectorModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.DSPGraphModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.DSPGraphModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.GameCenterModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.GameCenterModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.GIModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.GIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.GridModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.GridModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.HotReloadModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.HotReloadModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.ImageConversionModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.InputModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.JSONSerializeModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.JSONSerializeModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.LocalizationModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.LocalizationModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.NVIDIAModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.NVIDIAModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.ParticleSystemModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PerformanceReportingModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.PerformanceReportingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Physics2DModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.Physics2DModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PropertiesModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.PropertiesModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ScreenCaptureModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.ScreenCaptureModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.SharedInternalsModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.SharedInternalsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.SpatialTracking">
      <HintPath>$(ManagedGameRefs)\UnityEngine.SpatialTracking.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.SpriteMaskModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.SpriteMaskModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.SpriteShapeModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.SpriteShapeModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.StreamingModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.StreamingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.SubstanceModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.SubstanceModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.SubsystemsModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.SubsystemsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TerrainModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.TerrainModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TerrainPhysicsModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.TerrainPhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextCoreFontEngineModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.TextCoreFontEngineModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextCoreTextEngineModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.TextCoreTextEngineModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TilemapModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.TilemapModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TLSModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.TLSModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(ManagedGameRefs)\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIElementsModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.UIElementsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UmbraModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.UmbraModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityAnalyticsCommonModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.UnityAnalyticsCommonModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityAnalyticsModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.UnityAnalyticsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityConnectModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.UnityConnectModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityCurlModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.UnityCurlModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityTestProtocolModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.UnityTestProtocolModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestAssetBundleModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.UnityWebRequestAssetBundleModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestAudioModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.UnityWebRequestAudioModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.UnityWebRequestModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestTextureModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.UnityWebRequestTextureModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestWWWModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.UnityWebRequestWWWModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VehiclesModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.VehiclesModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VFXModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.VFXModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VideoModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.VideoModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VirtualTexturingModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.VirtualTexturingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VRModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.VRModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.WindModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.WindModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.XR.LegacyInputHelpers">
      <HintPath>$(ManagedGameRefs)\UnityEngine.XR.LegacyInputHelpers.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.XRModule">
      <HintPath>$(ManagedGameRefs)\UnityEngine.XRModule.dll</HintPath>
    </Reference>
    <Reference Include="Valve.Newtonsoft.Json">
      <HintPath>$(ManagedGameRefs)\Valve.Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="VoiceSDK.Dictation.Runtime">
      <HintPath>$(ManagedGameRefs)\VoiceSDK.Dictation.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="VoiceSDK.Runtime">
      <HintPath>$(ManagedGameRefs)\VoiceSDK.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="VYaml.Core">
      <HintPath>$(ManagedGameRefs)\VYaml.Core.dll</HintPath>
    </Reference>
    <Reference Include="websocket-sharp">
      <HintPath>$(ManagedGameRefs)\websocket-sharp.dll</HintPath>
    </Reference>
    <Reference Include="ZString">
      <HintPath>$(ManagedGameRefs)\ZString.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
